const stocks = [
  {
    symbol: "TCS",
    company: "Tata Consultancy Services",
    exchange: "BSE",
    currency: "INR",
    sector: "Information Technology",
    industry: "Information Technology Services",
    website: "https://www.tcs.com",
  },
  {
    symbol: "INFY",
    company: "Infosys",
    exchange: "BSE",
    currency: "INR",
    sector: "Information Technology",
    industry: "Information Technology Services",
    website: "https://www.infosys.com",
  },
  {
    symbol: "RELIANCE",
    company: "Reliance Industries",
    exchange: "NSE",
    currency: "INR",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    website: "https://www.relianceindustries.com",
  },
  {
    symbol: "HDFCBANK",
    company: "HDFC Bank",
    exchange: "NSE",
    currency: "INR",
    sector: "Financials",
    industry: "Banking",
    website: "https://www.hdfcbank.com",
  },
  {
    symbol: "ICICIBANK",
    company: "ICICI Bank",
    exchange: "NSE",
    currency: "INR",
    sector: "Financials",
    industry: "Banking",
    website: "https://www.icicibank.com",
  },
  {
    symbol: "SBIN",
    company: "State Bank of India",
    exchange: "BSE",
    currency: "INR",
    sector: "Financials",
    industry: "Banking",
    website: "https://www.sbi.co.in",
  },
  {
    symbol: "BHARTIARTL",
    company: "Bharti Airtel",
    exchange: "NSE",
    currency: "INR",
    sector: "Telecommunication Services",
    industry: "Wireless Communication",
    website: "https://www.airtel.in",
  },
  {
    symbol: "AXISBANK",
    company: "Axis Bank",
    exchange: "NSE",
    currency: "INR",
    sector: "Financials",
    industry: "Banking",
    website: "https://www.axisbank.com",
  },
  {
    symbol: "WIPRO",
    company: "Wipro",
    exchange: "BSE",
    currency: "INR",
    sector: "Information Technology",
    industry: "Information Technology Services",
    website: "https://www.wipro.com",
  },
  {
    symbol: "HINDUNILVR",
    company: "Hindustan Unilever",
    exchange: "NSE",
    currency: "INR",
    sector: "Consumer Staples",
    industry: "Household & Personal Products",
    website: "https://www.hul.co.in",
  },
  {
    symbol: "ITC",
    company: "ITC Ltd.",
    exchange: "BSE",
    currency: "INR",
    sector: "Consumer Staples",
    industry: "Tobacco",
    website: "https://www.itcportal.com",
  },
  {
    symbol: "LUPIN",
    company: "Lupin",
    exchange: "BSE",
    currency: "INR",
    sector: "Healthcare",
    industry: "Pharmaceuticals",
    website: "https://www.lupin.com",
  },
  {
    symbol: "MARUTI",
    company: "Maruti Suzuki",
    exchange: "BSE",
    currency: "INR",
    sector: "Consumer Discretionary",
    industry: "Automobile Manufacturers",
    website: "https://www.marutisuzuki.com",
  },
  {
    symbol: "DRREDDY",
    company: "Dr. Reddy's Laboratories",
    exchange: "BSE",
    currency: "INR",
    sector: "Healthcare",
    industry: "Pharmaceuticals",
    website: "https://www.drreddys.com",
  },
  {
    symbol: "M&M",
    company: "Mahindra & Mahindra",
    exchange: "NSE",
    currency: "INR",
    sector: "Consumer Discretionary",
    industry: "Automobile Manufacturers",
    website: "https://www.mahindra.com",
  },
  {
    symbol: "AAPL",
    company: "Apple",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "Information Technology",
    industry: "Consumer Electronics",
    website: "https://www.apple.com",
  },
  {
    symbol: "MSFT",
    company: "Microsoft",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "Information Technology",
    industry: "Software - Infrastructure",
    website: "https://www.microsoft.com",
  },
  {
    symbol: "GOOG",
    company: "Alphabet (Google)",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "Communication Services",
    industry: "Interactive Media & Services",
    website: "https://www.abc.xyz",
  },
  {
    symbol: "AMZN",
    company: "Amazon",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "Consumer Discretionary",
    industry: "Internet Retail",
    website: "https://www.amazon.com",
  },
  {
    symbol: "TSLA",
    company: "Tesla",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "Consumer Discretionary",
    industry: "Automobile Manufacturers",
    website: "https://www.tesla.com",
  },
  {
    symbol: "NVDA",
    company: "NVIDIA",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "Information Technology",
    industry: "Semiconductors",
    website: "https://www.nvidia.com",
  },
  {
    symbol: "META",
    company: "Meta Platforms",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "Communication Services",
    industry: "Interactive Media & Services",
    website: "https://www.meta.com",
  },
  {
    symbol: "NFLX",
    company: "Netflix",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "Communication Services",
    industry: "Movies & Entertainment",
    website: "https://www.netflix.com",
  },
  {
    symbol: "SPY",
    company: "SPDR S&P 500 ETF",
    exchange: "NYSE",
    currency: "USD",
    sector: "N/A",
    industry: "N/A",
    website: "https://www.spdrs.com",
  },
  {
    symbol: "JPM",
    company: "JPMorgan Chase",
    exchange: "NYSE",
    currency: "USD",
    sector: "Financials",
    industry: "Banking",
    website: "https://www.jpmorganchase.com",
  },
  {
    symbol: "BA",
    company: "Boeing",
    exchange: "NYSE",
    currency: "USD",
    sector: "Industrials",
    industry: "Aerospace & Defense",
    website: "https://www.boeing.com",
  },
  {
    symbol: "DIS",
    company: "Walt Disney",
    exchange: "NYSE",
    currency: "USD",
    sector: "Communication Services",
    industry: "Media",
    website: "https://www.thewaltdisneycompany.com",
  },
  {
    symbol: "V",
    company: "Visa",
    exchange: "NYSE",
    currency: "USD",
    sector: "Financials",
    industry: "Information Technology Services",
    website: "https://www.visa.com",
  },
  {
    symbol: "BAC",
    company: "Bank of America",
    exchange: "NYSE",
    currency: "USD",
    sector: "Financials",
    industry: "Banking",
    website: "https://www.bankofamerica.com",
  },
  {
    symbol: "VOD",
    company: "Vodafone",
    exchange: "LSE",
    currency: "GBP",
    sector: "Telecommunication Services",
    industry: "Wireless Communication",
    website: "https://www.vodafone.com",
  },
  {
    symbol: "RDSA",
    company: "Royal Dutch Shell",
    exchange: "LSE",
    currency: "GBP",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    website: "https://www.shell.com",
  },
  {
    symbol: "HSBC",
    company: "HSBC Holdings",
    exchange: "LSE",
    currency: "GBP",
    sector: "Financials",
    industry: "Banking",
    website: "https://www.hsbc.com",
  },
  {
    symbol: "BHP",
    company: "BHP Group",
    exchange: "LSE",
    currency: "GBP",
    sector: "Materials",
    industry: "Metals & Mining",
    website: "https://www.bhp.com",
  },
];

export default stocks;
